#!/usr/bin/env python3
"""Stage an anonymous, code-only supplementary release from the working repo.

This script lives in a directory inside the repository it releases: SRC is the
parent directory, STAGE is `supplementary/` next to this file, and this whole
directory is excluded from the release so the build never stages itself.

The source tree is read-only here: every file is copied into STAGE and rewritten
there. Nothing outside this directory is modified.

Shipped into STAGE: Python sources, requirements.txt, the detection-prompt
reference, a freshly written anonymous README, and a .gitignore.

Shipped next to STAGE, not inside it: the anonymized prior workshop paper this
submission extends, copied verbatim to OUT as prior_workshop_paper.pdf. It sits
at the root of the submission zip rather than inside the code tree so a reviewer
checking the dual-submission statement finds it without unpacking code/.

Not shipped: all result and data files (per-run JSONs, figure-search dumps,
contact sheets, logs), the project page under website/ (author names and
institution links), and the LaTeX sources under paper/ (prior workshop title).

Rewritten on the way out: absolute local paths (home directories, conda
environments, agent scratch directories, data mounts), the project's own
repository name, and any author or institution string.

Note: this wipes and rebuilds STAGE, including any git repository staged there.
Re-run `git init` and re-commit afterwards if you keep one.

Run:  python build_release.py
"""

import os
import re
import shutil
import subprocess

OUT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.dirname(OUT)
STAGE = os.path.join(OUT, "supplementary")
# This directory's path relative to the repository root, so the build never
# stages itself back into the release.
SELF = os.path.basename(OUT) + "/"

# Directories whose contents never ship, whatever the extension.
DROP_DIRS = (SELF, "website/", "paper/", ".claude/")
# Extensions that ship. Everything else is a result, a dataset, or an artifact.
KEEP_EXT = {".py"}
# Named exceptions: install manifest and the detection-prompt reference.
KEEP_FILES = {"requirements.txt", "detpo_map/PROMPTS.md"}
# The prior workshop paper, copied byte for byte to OUT rather than into STAGE.
# Its source is under paper/, which DROP_DIRS excludes, so it is handled on its
# own below and never passes through the text-scrubbing path: it is already
# anonymous (no author block, no institution, no acknowledgements, no venue and
# no self-citation), and rewriting bytes inside a PDF would corrupt it.
WORKSHOP_PDF_SRC = "paper/Anonymous_Workshop_Paper.pdf"
WORKSHOP_PDF_OUT = "prior_workshop_paper.pdf"

PATH_SUBS = [
    # Agent scratch directories, which also carry session ids.
    (r"remote:/tmp/[a-z]+-\d+[^\s\"',)\]]*", "remote-reflector"),
    (r"/tmp/[a-z]+-\d+/[^\s\"',)\]]*?/scratchpad", "./scratch"),
    (r"/tmp/[a-z]+-\d+/-home-[^\s\"',)\]]*", "./scratch"),
    # Personal conda environments.
    (r"/home/[a-z0-9_]+/anaconda3/envs/[A-Za-z0-9_.-]+/bin/python", "python"),
    (r"/home/[a-z0-9_]+/(ana|mini)conda3/envs/[A-Za-z0-9_.-]+", "$CONDA_PREFIX"),
    # External sibling projects and dataset roots.
    (r"/home/[a-z0-9_]+/Research/middle_layers_indicating_hallucinations/"
     r"naturalbench/probe", "mechanism_results"),
    (r"/home/[a-z0-9_]+/Research/rf-20-vl-benchmark/datasets", "datasets"),
    (r"/home/[a-z0-9_]+/Research/DetPO", "third_party/DetPO"),
    (r"/home/[a-z0-9_]+/Research/ask-twice-look-twice-supp", "."),
    (r"/home/[a-z0-9_]+/Research/([A-Za-z0-9_.-]+)", r"../\1"),
    (r"/home/[a-z0-9_]+/", "~/"),
    (r"/data\d*/datasets", "datasets"),
    (r"/data\d*/hf_cache", "hf_cache"),
    (r"/data\d*/([A-Za-z0-9_.-]+)", r"data/\1"),
    # The repository name is the prior workshop title, which is public.
    (r"ask-twice-look-twice-supp", "vlm-prompt-ordering"),
    (r"ask-twice-look-twice", "vlm-prompt-ordering"),
    (r"Ask Twice,? Look Twice", "Position, Not Content"),
    # Author and institution strings.
    (r"Rakshanda Hassan Abhinandan", "Anonymous Author"),
    (r"Gautam Rajendrakumar Gare", "Anonymous Author"),
    (r"[0-9]*\+?rakshanda-cmu@users\.noreply\.github\.com", "anon@example.com"),
    (r"[0-9]*\+?ggare-cmu@users\.noreply\.github\.com", "anon@example.com"),
    (r"rakshanda\.ha@gmail\.com", "anon@example.com"),
    (r"rakshanda-cmu", "anonymous"),
    (r"ggare-cmu", "anonymous"),
    (r"\bRakshanda\b", "Anonymous"),
    (r"\bGautam\b", "Anonymous"),
    (r"\bggare\b", "anonymous"),
    (r"Deva Ramanan", "Anonymous"),
    (r"John Galeotti", "Anonymous"),
    (r"Carnegie Mellon University", "Anonymous Institution"),
    (r"Carnegie Mellon", "Anonymous Institution"),
]

GITIGNORE = """# Model weights and checkpoints
*.safetensors
*.bin
*.pt
*.pth
models/

# Datasets and images: download separately, see README
datasets/
COCO/
naturalbench/
pope/
winoground/
rf20/
vqa/

# Run outputs: every result file is regenerated by the scripts in this repo
results/
*/results/
gepa_results/
*_results.json
figs/
*.gif
*.log

# Python
__pycache__/
*.pyc
.venv/
venv/
.env
.ipynb_checkpoints/
.DS_Store
"""


EXTRA_REQUIREMENTS = """
# ---- Benchmark sweeps and baselines (install as needed) ----
vllm                         # the extra_tasks/ and detpo_map/ *_eval_vllm.py harnesses
qwen-vl-utils                # Qwen3-VL / Qwen2.5-VL image and video preprocessing
gepa                         # GEPA prompt-optimization baseline
openai                       # OpenAI-compatible client for reflection_server.py
# llava                      # LLaVA-1.5-7B, install from its own repository
"""


def tracked_files():
    out = subprocess.run(["git", "-C", SRC, "ls-files", "-z"],
                         capture_output=True, text=True, check=True)
    return [p for p in out.stdout.split("\0") if p]


def keep(rel):
    if rel.startswith(DROP_DIRS):
        return False
    if rel in KEEP_FILES:
        return True
    return os.path.splitext(rel)[1] in KEEP_EXT


def scrub(text):
    for pat, repl in PATH_SUBS:
        text = re.sub(pat, repl, text)
    return text


def main():
    if os.path.exists(STAGE):
        shutil.rmtree(STAGE)
    os.makedirs(STAGE)

    copied = scrubbed = 0
    for rel in tracked_files():
        src = os.path.join(SRC, rel)
        if not keep(rel) or not os.path.exists(src):
            continue
        dst = os.path.join(STAGE, rel)
        os.makedirs(os.path.dirname(dst) or STAGE, exist_ok=True)
        with open(src, errors="surrogateescape") as fh:
            text = fh.read()
        new = scrub(text)
        with open(dst, "w", errors="surrogateescape") as fh:
            fh.write(new)
        copied += 1
        scrubbed += new != text

    src_pdf = os.path.join(SRC, WORKSHOP_PDF_SRC)
    if not os.path.exists(src_pdf):
        raise SystemExit(
            f"missing {WORKSHOP_PDF_SRC}: the submission cites the prior "
            "workshop paper as supplementary material, so the release must not "
            "be built without it")
    shutil.copy2(src_pdf, os.path.join(OUT, WORKSHOP_PDF_OUT))

    with open(os.path.join(STAGE, ".gitignore"), "w") as fh:
        fh.write(GITIGNORE)

    shutil.copy2(os.path.join(OUT, "README_release.md"),
                 os.path.join(STAGE, "README.md"))

    # The source requirements.txt covers the analysis and figure code but not the
    # sweep and baseline runtimes, which are imported by scripts that ship here.
    with open(os.path.join(STAGE, "requirements.txt"), "a") as fh:
        fh.write(EXTRA_REQUIREMENTS)

    print(f"staged {copied} source files, rewrote paths in {scrubbed}")
    print(f"copied {WORKSHOP_PDF_SRC} to {WORKSHOP_PDF_OUT} for the zip root")


if __name__ == "__main__":
    main()
